### ISSUE TITLE
Add support for Redis memcaching

### ISSUE THREAD

**Issue by djjudas21** [bitnami/bitnami-docker-owncloud#68]
**Description**

I have installed owncloud from the [Bitnami helm chart](https://github.com/bitnami/charts/tree/master/bitnami/owncloud). When I start it up, the admin page gives me some warnings:

* Transactional file locking should be configured to use memory-based locking, not the default slow database-based locking. See the documentation ↗ for more information.
* No memory cache has been configured. To enhance your performance please configure a memcache if available. Further information can be found in our documentation.

Therefore, I suggest adding support to configure a memory cache like Redis in this image, configured similarly to MySQL. I guess you would need to add the Redis client in the image, and add support for at least the following environment variables:

```
  OWNCLOUD_REDIS_ENABLED: "true"
  OWNCLOUD_REDIS_HOST: redis
```

It would then be easy to add support to the Helm chart also.

I don't know much about the Bitnami images work internally, but I'm happy to submit a PR for the Helm chart when support for Redis is available in this image. Thanks.

**Comment by yilmi** [comment]
I was just trying to be helpful, don't worry this is tracked on our end and hopefully we'll pick it up soon. Thanks for reporting it!

**Comment by fmulero** [comment]
This is a community-supported solution. This means that the Bitnami team is not actively working on new features/improvements nor providing support through GitHub Issues for this container.

The Bitnami team will review any PR that is created, feel free to create a PR if you find any issue or want to implement a new feature.

We are also moving to [a new repository](https://github.com/bitnami/containers) in order to be aligned with the approach followed in [bitnami/charts](https://github.com/bitnami/charts). More information [here](https://blog.bitnami.com/2022/07/new-source-of-truth-bitnami-containers.html). If you are still interested on this feature, please open a new issue in [bitnami/containers](https://github.com/bitnami/containers) repository
